version: 2
jobs:
  build__PY_27:
    environment:
      - INSTALL_EDM_VERSION: "1.11.0"
      - RUNTIME_VERSION: "2.7"
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing other packages
          command: 'apt-get update && apt-get install -y gcc g++ curl git'
      - run:
          name: Installing Cmake
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Git Submodules
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Install edm and dependencies
          command: |
            ./ci/install-edm-linux.sh
            ./ci/install-environment.sh
      - run:
          name: Run tests
          command: ./ci/run-tests.sh
  build__PY_36:
    environment:
      - INSTALL_EDM_VERSION: "1.11.0"
      - RUNTIME_VERSION: "3.6"
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing other packages
          command: 'apt-get update && apt-get install -y gcc g++ curl git'
      - run:
          name: Installing Cmake
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Git Submodules
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Install edm and dependencies
          command: |
            ./ci/install-edm-linux.sh
            ./ci/install-environment.sh
      - run:
          name: Run tests
          command: ./ci/run-tests.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build__PY_27
      - build__PY_36
